dist: xenial

language: go

matrix:
  include:
    - go: "1.12.x"
      env: GO111MODULE=on
    - go: "1.13.x"
      env: GO111MODULE=on COVERAGE=true
    - go: "tip"
      env: GO111MODULE=on
  allow_failures:
    - go: "1.12.x"
      env: GO111MODULE=on
    - go: "tip"
      env: GO111MODULE=on
  fast_finish: true

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - $GOPATH/pkg
    - $HOME/.cache/go-build

before_install:
  - GO111MODULE=off go get -v -u github.com/mattn/goveralls
  - docker pull zikaeroh/postgres-initialized
  - docker pull nsqio/nsq

script:
  - go mod tidy
  - test -z "$(git status --porcelain go.mod go.sum)"
  - go test -race -covermode=atomic -coverprofile=cover.out ./...
  - if [ "$COVERAGE" = true ]; then $GOPATH/bin/goveralls -service=travis-ci -coverprofile=cover.out; fi
