[psql]

# postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable

dbname = "postgres"
host = "localhost"
user = "postgres"
pass = "mysecretpassword"
sslmode = "disable"
blacklist = ["schema_migrations"]

